name: pull request to release

on:
  pull_request:
    branches:
      - release/**/*
    types:
      - edited

jobs:
  on-pr-edit-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Prefix pull request title
        uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: '[feat],[fix],[docs],[style],[refactor],[perf],[test],[build],[ci],[chore],[revert]'
          prefix_case_sensitive: true
          github_token: ${{ github.token }}

      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
