name: pull request to release

on:
  pull_request:
    branches:
      - release/**/*

jobs:
  on-pr-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Prefix pull request title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '/^([feat]|[fix]|[docs]|[style]|[refactor]|[test]|[build]|[ci]|[chore])+([angular-material]|[icons]|[interactions]|[ionic-5]|[ionic-6]|[ionic-7]|[ionic-8]|[shared]|[tokens]|[utilities]|[web-components])+([a-z])+\/([a-z])+$/;'
          prefix_case_sensitive: true
          github_token: ${{ github.token }}

      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
