name: pull request closed to main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  on-pr-closed-to-main:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install changelog generator
        run: |
          curl -sSL https://github.com/git-chglog/git-chglog/releases/download/v0.10.0/git-chglog_0.10.0_linux_amd64.tar.gz | tar -xz -C /usr/local/bin

      - name: Generate Changelog
        run: |
          # Generate changelog from git history (adjust options as necessary)
          git-chglog --next-tag v$(date +%Y.%m.%d) --output CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Update changelog for PR merge: ${{ github.event.pull_request.title }}"
          git push

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
