name: pull request edition to main

on:
  pull_request:
    branches:
      - main
    types:
      - edited

jobs:
  on-pr-edition-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Prefix pull request title edition
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[(root|angular-material|icons|interactions|ionic-5|ionic-6|ionic-7|ionic-8|shared|tokens|utilities|web-components)\]\[(feat|fix|docs|style|refactor|test|build|ci|chore)\] [a-z]+( .*)*$'
          github_token: ${{ github.token }}

      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
