name: pull request opening to main

on:
  pull_request:
    branches:
      - main

jobs:
  on-pr-opening-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Prefix pull request title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\d+\.\d+\.\d+$'
          github_token: ${{ github.token }}
